### ISSUE TITLE
Licence & Library

### ISSUE THREAD

**Issue by the8472** [iirelu/braillify#2]
I would like to use the ToBraille trait as a library. Is your code available under an open source license?

**Comment by iirelu** [comment]
Whoops, didn't even realise I forgot to include one. Added MIT, let me know if you need a crate version bump for what you're doing.

**Comment by the8472** [comment]
Thanks. The crate is currently binary-only (no lib.rs) so I would actually have to steal the source to use that module. With appropriate license information of course.

**Comment by iirelu** [comment]
Ah, I totally forgot I left this project half abandoned. I can turn it into a real library if there's interest in that.
